"""Pydantic models for API request and response payloads."""

from typing import List, Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Schema describing a chat completion request."""

    message: str = Field(..., description="The user message to send to the assistant.")
    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional conversation identifier for maintaining context.",
    )


class ChatResponse(BaseModel):
    """Schema describing a chat completion response."""

    conversation_id: str
    response: str
    reasoning_steps: Optional[List[str]] = Field(
        default=None,
        description="Optional list of reasoning steps generated by the model.",
    )
    retrieved_context: Optional[List[str]] = Field(
        default=None,
        description="Contextual snippets retrieved from the vector store.",
    )


class HealthResponse(BaseModel):
    """Simple health status response."""

    status: str = Field(..., description="High-level service status.")
    details: Optional[str] = Field(default=None, description="Additional diagnostic detail.")
